name: Second Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello twice
        run:  |
            echo "Hello"
            echo "Hello"
      - name: Print Bye twice
        run:  |
            echo "Bye"
            echo "Bye"
